# -*- coding: utf-8 -*-
"""analise_frente_estruturadoprojeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK3RzxcVCSvcy2Rm3-tzYW2CSZC3ZQSF
"""

import os
import git
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from sklearn.manifold import TSNE
from transformers import AutoTokenizer, AutoModel
from google.colab import drive

# 0. MONTAR GOOGLE DRIVE
drive.mount('/content/drive')
BASE_DIR = "/content/drive/MyDrive/ENG_SOFT_II/LangExtract_analysis"
os.makedirs(BASE_DIR, exist_ok=True)

# CONFIGURAÇÕES
REPO_URL = "https://github.com/google/langextract.git"
REPO_PATH = "./langextract_repo"
MODEL_NAME = "bert-base-uncased"
OUTPUT_FILE = os.path.join(BASE_DIR, "resultados_frente3.txt")
PLOT_FILE = os.path.join(BASE_DIR, "estrutura_projeto_frente3.png")

# 1. CLONAR O REPOSITÓRIO
if not os.path.exists(REPO_PATH):
    print(f"Clonando repositório {REPO_URL}...")
    git.Repo.clone_from(REPO_URL, REPO_PATH)
else:
    print("Repositório já existe localmente.")

# 2. LISTAR ESTRUTURA DE PASTAS
pasta_raiz = Path(REPO_PATH)
pastas = sorted([str(p.relative_to(pasta_raiz)) for p in pasta_raiz.glob("*/") if ".git" not in str(p)])

print(f"Foram encontradas {len(pastas)} pastas principais:")
for p in pastas:
    print(" -", p)

# 3. CARREGAR MODELO BERT
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsando dispositivo: {device}")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME).to(device)

# 4. EXTRAIR EMBEDDINGS DAS PASTAS
def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to(device)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()

embeddings = [get_embedding(p) for p in pastas]
print("\nEmbeddings extraídos com sucesso!")

# 5. REDUÇÃO DE DIMENSIONALIDADE
tsne = TSNE(n_components=2, perplexity=5, random_state=42)
embeddings_array = np.array(embeddings)
reduced = tsne.fit_transform(embeddings_array)

df = pd.DataFrame({
    "pasta": pastas,
    "x": reduced[:, 0],
    "y": reduced[:, 1]
})

# 6. PLOTAR RESULTADOS
plt.figure(figsize=(8, 6))
plt.scatter(df["x"], df["y"], c="blue", s=80)

for _, row in df.iterrows():
    plt.text(row["x"] + 0.5, row["y"], row["pasta"], fontsize=9)

plt.title("Análise de Estrutura de Pastas - LangExtract (Frente 3)")
plt.xlabel("Dimensão 1")
plt.ylabel("Dimensão 2")
plt.grid(True)
plt.tight_layout()
plt.savefig(PLOT_FILE)
plt.show()

# 7. SALVAR RESULTADOS
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("=== RELATÓRIO - FRENTE 3: Estrutura de Projeto ===\n\n")
    f.write(f"Repositório: {REPO_URL}\n")
    f.write(f"Modelo: {MODEL_NAME}\n\n")
    f.write("Pastas analisadas:\n")
    for p in pastas:
        f.write(f" - {p}\n")
    f.write("\nCoordenadas 2D geradas (t-SNE):\n\n")
    for _, row in df.iterrows():
        f.write(f"{row['pasta']}: ({row['x']:.2f}, {row['y']:.2f})\n")

print(f"\n✅ Análise concluída! Resultados salvos em:")
print(f"- {OUTPUT_FILE}")
print(f"- {PLOT_FILE}")
!ls -lh "$BASE_DIR"
